musicapp/urls.py
from django.conf.urls import patterns, url

from musicapp import views

urlpatterns = patterns('',
    url(r'^thanks/$', views.thanks, name='thanks'),
    url(r'^edit_score/$', views.edit_score, name='edit_score'),
    url(r'^display_score/(?P<score_id>\w+)/$', views.display_score, name='display_score'),
    url(r'^embed_score/(?P<score_id>\w+)/$', views.embed_score, name='embed_score'),
    #url(r'^edit_fretboard/$', views.edit_fretboard, name='edit_fretboard'),
    #url(r'^display_fretboard/(?P<score_id>\w+)/$', views.display_fretboard, name='display_fretboard'),
    #url(r'^embed_fretboard/(?P<score_id>\w+)/$', views.embed_fretboard, name='embed_fretboard'),
    url(r'^$', views.index, name='index'),
)

musicpaste/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'musicpaste.views.index', name='index'),
    url(r'^$', include('musicapp.urls')),
    # url(r'^blog/', include('blog.urls')),

    url(r'^musicapp/', include('musicapp.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

musicapp/models.py
from django.db import models

#unique ID
import shortuuid
#For the moment use normal uuid and see
#import uuid

# Create your models here.
def random_uuid():
    return shortuuid.ShortUUID().random(length=22)
    
class Sheet(models.Model):
    """
    """
    suuid = models.CharField(max_length=64, default=random_uuid, editable=False) 
    #suuid = models.CharField(max_length=64, default=str(uuid.uuid4()).replace('-',''), editable=False)
    title = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    description = models.TextField(max_length=512)
    content = models.TextField(max_length=8192)

musicapp/forms.py
from django import forms
from django.forms import ModelForm, Form
from musicapp.models import Sheet

from django.core.validators import validate_slug
from django.core.exceptions import ValidationError

################################################################################
#Custom validators
################################################################################
def vextab_validator(content):
    """
    For the moment only tries to avoid javascript injection
    #TODO Validates that the input contains valid vextab format
    """
    #TODO make a real VexTab validator format
    if content.find("'") >= 0 or content.find('"') >= 0 or content.find("javascript") >= 0:
        raise ValidationError("Vextab Invalid content detected")
    

################################################################################
#Forms
################################################################################

class SheetForm(ModelForm):
    title = forms.CharField(max_length=100, required=True)
    name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField(max_length=254, required=True)
    #description = forms.CharField(max_length=512, required=False, validators=[validate_slug])  # TODO make it better to support punctuation symbols
    description = forms.CharField(max_length=512, required=False)
    content = forms.CharField(max_length=8192, required=True,
                                validators=[vextab_validator]) 
    class Meta:
        model = Sheet

musicapp/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
#shortcuts
from django.shortcuts import get_object_or_404
#email
from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
#templates
from django.template import loader, Context

#
from django.views.decorators.clickjacking import xframe_options_exempt

#forms
from musicapp.forms import SheetForm
#models
from musicapp.models import Sheet

import sys

#INDEX
def index(request):
    """
    """
    return render(request, 'musicapp/index.html')

################################################################################
#scores
################################################################################

def edit_score(request):
    """
    """
    if request.method == 'POST': # If the form has been submitted...
        form = SheetForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            new_sheet = form.save()
            #print "new sheet = ", new_sheet
            # links to see the results (embed and display)
            subject = "Hi %s! Here your newly created music sheets" % new_sheet.name
            embed_link = request.build_absolute_uri(reverse('embed_score', args=[new_sheet.suuid]))
            display_link = request.build_absolute_uri(reverse('display_score', args=[new_sheet.suuid]))
            #build email
            email_context = {"subject": subject,
                             "name": new_sheet.name,
                             "title": new_sheet.title,
                             "embed_link": embed_link,
                             "display_link": display_link,
                             }
            htmly = loader.get_template('simple_basic_inlined.email')
            plaintext = loader.get_template('simple_basic.txt')
            c = Context(email_context)
            #print >> sys.stderr, "sending email"
            #sys.stderr.flush()
            #try:
            from_email = 'MusicPaste - Link Service <no-reply@musicpaste.com>'
            text_content = plaintext.render(c)
            html_content = htmly.render(c)
            msg = EmailMultiAlternatives(subject, text_content, from_email, [new_sheet.email])
            msg.attach_alternative(html_content, "text/html")
            msg.send()
            #print >> sys.stderr, "email sent"
            #sys.stderr.flush()
            #except Exception as e:
            #    print "ERROR sending email: ", e
            #    sys.stdout.flush()
            #TODO redirect to page error
            #Redirect if everything went great
            return HttpResponseRedirect(reverse('thanks')) # Redirect after POST
        else:
            print "The form is not valid"
            print form.errors
            #print "is not valid because ... ?"
            #reload the page but with the elements given already pre-filled 
            #and a warning telling about the errors
            #TODO modify the template to take in account the given post data
            return render(request, 'musicapp/edit_score.html', {
                'form': form,
            })
    else:
        return render(request, 'musicapp/edit_score.html')

    


def display_score(request,score_id):
    """
    """
    context = {}
    #find the score by the given input score_id, redirect to 404 if not found
    sheet = get_object_or_404(Sheet, suuid=score_id)
    context["sheet"] = sheet
    return render(request, 'musicapp/display_score.html', context)
        
@xframe_options_exempt
def embed_score(request, score_id):
    """
    """
    context = {}
    #find the score by the given input score_id, redirect to 404 if not found
    sheet = get_object_or_404(Sheet, suuid=score_id)
    context["sheet"] = sheet
    return render(request, 'musicapp/embed_score.html', context)

################################################################################
#
################################################################################

def thanks(request):
    """
    """
    return render(request, 'musicapp/thanks.html')

musicapp/templates/footer_ga.html
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-53689016-1', 'auto');
  ga('send', 'pageview');

</script>

musicapp/templates/musicapp/base_score.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
{% load compress %}
{% block header %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MusicPaste, Awesome, embeddable music TABs and scores with sound synthesis</title>
    {% compress css %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'musicapp/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'musicapp/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <style>
    .editable {
        width:95%;
        height: 100%;
        border-style: solid;
        border-width: 1px;
        
    }
    .editable:hover {
        background-color:#eeeeee;
    } 
    </style>
    {% endcompress %}
</head>
{% endblock %}

{%block body%}
<body >
    {% block navbar %}
    <!--<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#home">MusicPaste</a>
            </div>
        </div>
    </nav>-->
    <br/>
    {% endblock %}
    <div class="container">
    {% block content %}
    {% endblock %}
        {% block footer %}
        <hr>
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <a href="http://musicpaste.com"> MusicPaste</a> 2014</p>
                </div>
            </div>
        </footer>
        {% endblock %}
    </div>
    <!-- /.container -->
{% block scripts %}
    <!-- JavaScript -->
    <script src="{% static 'musicapp/js/jquery-1.10.2.js' %}"></script> <!-- TODO update version-->
    <!--<script src="js/bootstrap.min.js"></script>-->
    <script src="{% static 'musicapp/js/underscore-min.js' %}"></script>
    <script src="{% static 'musicapp/js/bootstrap.js' %}"></script>
    
    
    <script src="{% static 'musicapp/js/angular.min.js' %}"></script>
    <!--<script src="js/angular-route.js"></script>-->
    <script src="{% static 'musicapp/js/ui-bootstrap-tpls-0.11.0.min.js' %}"></script>
    
    
    


    {% compress js %}
        <!-- Base64 - for midi font loading-->
    <script src="{% static 'musicapp/js/base64-binary.js' %}"></script>
    <!-- Paper JS - for midi player graphics-->
    <script src="{% static 'musicapp/js/paper-core.min.js' %}"></script>

    <script src="{% static 'musicapp/js/MIDI.min.js' %}"></script>
        
    <script src="{% static 'musicapp/js/vexflow-min.js' %}"></script>
    
    <script src="{% static 'musicapp/js/tabdiv-min.js' %}"></script>

    <script src="{% static 'musicapp/js/musicpaste.js' %}"></script>
    {% endcompress %}
    

{% endblock %}

    {% include "footer_ga.html" %}
</body>
{% endblock %}
</html>

musicapp/templates/musicapp/display_score.html
{% extends "musicapp/base_score.html" %}
    {% block content %}
        <div class="row">
        
            <div class="col-lg-12 col-md-12">
                {% block page-header %}
                <h1 class="page-header">
                    <a href='/'>MusicPaste</a>
                    <small>The easiest way to create and share music</small>
                </h1>
                {% endblock %}
            
            {% block sheet-meta %}
            <div class="row center">
                <h2> {{sheet.title}} </h2>
                by: {{sheet.name}}
            </div>
            <div class="row">
                {{sheet.description}}
            </div>
            {% endblock %}
            </div>

        </div>
        <hr>
        {% block sheet-all %}
        <div class="row" ng-app="MusicPaste">
            <div ng-controller="vextabController" ng-init="initText('{{sheet.content}}')">
                {% block sheet-display-all%}
                <div class="col-lg-7 col-md-7">
                        {% block sheet-display-controls %}
                        <div>
                            <div class="col-lg-6 col-md-6">
                                <a class="btn btn-default btn-lg" ng-click="play()">
                                    <i class="fa fa-play fa-fw"></i>
                                    <span class="network-name">Play</span>
                                </a>
                                <a class="btn btn-default btn-lg" ng-click="stop()">
                                    <i class="fa fa-stop fa-fw"></i>
                                    <span class="network-name">Stop</span>
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-6">
                            <!--Select your instrument:--> 
                                <select ng-model="selectedTempo" ng-change="onSelectTempo(selectedTempo)" ng-options="tempo for tempo in tempos"></select>
                                <select ng-model="selectedInstrument" ng-change="onSelectInstrument(selectedInstrument)" ng-options="instrument for instrument in instruments"></select>
                            </div>
                        </div>
                        {% endblock %}
                        {% block sheet-display %}
                        <div>
                            <div data-vextab-paper="vextabText">
                            </div>
                        </div>
                        {% endblock %}
                </div>
                {% endblock %}
                {% block sheet-input %}
                <div class="col-lg-5 col-md-5" >
                    <div >
                        <textarea form="save-form" id="id_content" name= "content" ng-model="vextabText" class="editor editable" rows="30" columns="40" maxlength="8192">{{sheet.content}}</textarea>
                    </div>
                    
                </div>
                {% endblock %}
            </div>
        </div>
        {% endblock %}
    {% endblock %}

musicapp/templates/musicapp/edit_fretboard.html
{% extends "musicapp/base_score.html" %}

    {% block content %}
        <div class="row">
        
            <div class="col-lg-12 col-md-12">
                {% block page-header %}
                <h1 class="page-header">
                    <a href='/'>MusicPaste</a>
                    <small>The easiest way to create and share music</small>
                </h1>
                {% endblock %}
            
            {% block modal-form %}
            <!-- Button trigger modal -->
            <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
              <span class="fa fa-save fa-fw"></span> Save & <span class="fa fa-share fa-fw"></span> Share
            </button>
            
                <!-- Modal -->
                <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                    
                        <!-- Little x button to close this modal -->
                        <div class="modal-header" style="border: none">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        </div>
                      <div class="modal-body" style="padding: 0px 20px 20px 20px">
                        
                        <form role="form" id="save-form" action="{% url 'edit_score' %}" method="post">
                          {% csrf_token %}
                          <div class="form-group">
                            <label for="id_title">Title</label>
                            <input type="text" class="form-control" id="id_title" maxlength="100" name="title" placeholder="Title" required="true">
                          </div>
                          <div class="form-group">
                            <label for="id_name">Your name</label>
                            <input type="text" class="form-control" id="id_name" maxlength="100" name="name" placeholder="Your name"  required="true">
                          </div>
                          <div class="form-group">
                            <label for="id_email">Email</label>
                            <input type="email" class="form-control" id="id_email" maxlength="254" name="email" placeholder="Enter email"  required="true">
                          </div>
                          <div class="form-group">
                            <label for="id_description">Description</label>
                            <textarea cols="40" class="form-control" id="id_description" name="description" rows="10" placeholder="Description"></textarea>
                          </div>
                        
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <!--button type="button" class="btn btn-primary">
                                <span class="fa fa-save fa-fw"></span> Save & <span class="fa fa-share fa-fw"></span> Share
                            </button-->
                            <button type="submit" class="btn btn-primary"><span class="fa fa-save fa-fw"></span> Save & <span class="fa fa-share fa-fw"></span> Share</button>
                        </form>
                      </div> <!-- /.modal-body -->
                      
                    </div>
                  </div>
                </div> <!-- /.modal -->
            {% endblock %}
            </div>

        </div>
        <hr>
        {% block fretboard-all %}
        <div class="row" ng-app="MusicPaste">
            <div ng-controller="fretboardController">
                {% block fretboard-display-all %}
                <div class="col-lg-7 col-md-7">
                        {% block fretboard-display %}
                        <div>
                            <div data-fretboard-paper="fretboardText">
                            </div>
                            <div data-fretboard-paper="fretboardLevel" id="fretboardContainer">
                                <div id="fretboardDiv"></div>
                                <div id="dummyDiv"></div>
                            </div>
                        </div>
                        {% endblock %}
                </div>
                {% endblock %}
                {% block fretboard-input %}
                <div class="col-lg-5 col-md-5" >
                    <div>
                          <h2 style="color:#B41E00;">
                            <i class="fa fa-arrow-down"></i> 
                            Edit the text below
                          </h2>
                    </div>
                    <div>
                        <textarea form="save-form" id="id_content" name= "content" ng-model="fretboardText" class="editor editable" rows="25" columns="40" maxlength="1024"></textarea>
                    </div>
                    <div class="parseResults" style="color:#960003;" ng-show="parseOK === false">
                        <p>
                        Parse Error:
                        </p>
                        <p id="parseError" ><pre style="background-color:#ecc7c8;">{$ parseError $}</pre></p>
                    </div>                    
                </div>
                {% endblock %}
            </div>
        </div>
        {% endblock %}
    {% endblock %}


musicapp/templates/musicapp/edit_score.html
{% extends "musicapp/base_score.html" %}

    {% block content %}
        <div class="row">
        
            <div class="col-lg-12 col-md-12">
                {% block page-header %}
                <h1 class="page-header">
                    <a href='/'>MusicPaste</a>
                    <small>The easiest way to create and share music</small>
                </h1>
                {% endblock %}
            
            {% block modal-form %}
            <!-- Button trigger modal -->
            <button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
              <span class="fa fa-save fa-fw"></span> Save & <span class="fa fa-share fa-fw"></span> Share
            </button>
            
                <!-- Modal -->
                <div class="modal fade bs-example-modal-sm" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-sm">
                    <div class="modal-content">
                    
                        <!-- Little x button to close this modal -->
                        <div class="modal-header" style="border: none">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        </div>
                      <div class="modal-body" style="padding: 0px 20px 20px 20px">
                        
                        <form role="form" id="save-form" action="{% url 'edit_score' %}" method="post">
                          {% csrf_token %}
                          <div class="form-group">
                            <label for="id_title">Title</label>
                            <input type="text" class="form-control" id="id_title" maxlength="100" name="title" placeholder="Title" required="true">
                          </div>
                          <div class="form-group">
                            <label for="id_name">Your name</label>
                            <input type="text" class="form-control" id="id_name" maxlength="100" name="name" placeholder="Your name"  required="true">
                          </div>
                          <div class="form-group">
                            <label for="id_email">Email</label>
                            <input type="email" class="form-control" id="id_email" maxlength="254" name="email" placeholder="Enter email"  required="true">
                          </div>
                          <div class="form-group">
                            <label for="id_description">Description</label>
                            <textarea cols="40" class="form-control" id="id_description" name="description" rows="10" placeholder="Description"></textarea>
                          </div>
                        
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            <!--button type="button" class="btn btn-primary">
                                <span class="fa fa-save fa-fw"></span> Save & <span class="fa fa-share fa-fw"></span> Share
                            </button-->
                            <button type="submit" class="btn btn-primary"><span class="fa fa-save fa-fw"></span> Save & <span class="fa fa-share fa-fw"></span> Share</button>
                        </form>
                      </div> <!-- /.modal-body -->
                      
                    </div>
                  </div>
                </div> <!-- /.modal -->
            {% endblock %}
            </div>

        </div>
        <hr>
        {% block sheet-all %}
        <div class="row" ng-app="MusicPaste">
            <div ng-controller="vextabController">
                {% block sheet-display-all %}
                <div class="col-lg-7 col-md-7">
                        {% block sheet-display-controls %}
                        <div>
                            <div class="col-lg-6 col-md-6">
                                <a class="btn btn-default btn-lg" ng-click="play()">
                                    <i class="fa fa-play fa-fw"></i>
                                    <span class="network-name">Play</span>
                                </a>
                                <a class="btn btn-default btn-lg" ng-click="stop()">
                                    <i class="fa fa-stop fa-fw"></i>
                                    <span class="network-name">Stop</span>
                                </a>
                            </div>
                            <div class="col-lg-6 col-md-6">
                            <!--Select your instrument:--> 
                                <select ng-model="selectedTempo" ng-change="onSelectTempo(selectedTempo)" ng-options="tempo for tempo in tempos"></select>
                                <select ng-model="selectedInstrument" ng-change="onSelectInstrument(selectedInstrument)" ng-options="instrument for instrument in instruments"></select>
                            </div>
                        </div>
                        {% endblock %}
                        {% block sheet-display %}
                        <div>
                            <div data-vextab-paper="vextabText">
                            </div>
                        </div>
                        {% endblock %}
                </div>
                {% endblock %}
                {% block sheet-input %}
                <div class="col-lg-5 col-md-5" >
                    <div>
                          Edit the text below:
                    </div>
                    <div>
                        <textarea form="save-form" id="id_content" name= "content" ng-model="vextabText" class="editor editable" rows="25" columns="40" maxlength="8192"></textarea>
                    </div>
                    <div class="parseResults" style="color:#960003;" ng-show="parseOK === false">
                        <p>
                        Parse Error:
                        </p>
                        <p id="parseError" ><pre style="background-color:#ecc7c8;">{$ parseError $}</pre></p>
                    </div>                    
                </div>
                {% endblock %}
            </div>
        </div>
        {% endblock %}
    {% endblock %}


musicapp/templates/musicapp/embed_score.html
{% extends "musicapp/base_score.html" %}

    {% block content %}
        {% block sheet-all %}
        <div class="row" ng-app="MusicPaste">
            <div ng-controller="vextabController" ng-init="initText('{{sheet.content}}')">
                {% block sheet-display-all%}
                <div class="col-lg-12 col-md-12  col-sm-12">
                        {% block sheet-display-controls %}
                        <div>
                            <div class="col-lg-6 col-md-6  col-sm-6">
                                <strong >  {{sheet.title}}  </strong> by: {{sheet.name}}
                                
                                <a class="btn btn-default btn-sm" ng-click="play()">
                                    <i class="fa fa-play fa-fw"></i>
                                </a>
                                <a class="btn btn-default btn-sm" ng-click="stop()">
                                    <i class="fa fa-stop fa-fw"></i>
                                </a>
                                
                            <!--Select your instrument:--> 
                                BPM: <select ng-model="selectedTempo" ng-change="onSelectTempo(selectedTempo)" ng-options="tempo for tempo in tempos"></select>
                                <select ng-model="selectedInstrument" ng-change="onSelectInstrument(selectedInstrument)" ng-options="instrument for instrument in instruments"></select>
                                <br/>
                                <small> Made with: &copy; <a href="http://musicpaste.com"> MusicPaste</a></small>
                        </div>
                        {% endblock %}
                        {% block sheet-display %}
                        <div>
                            <div data-vextab-paper="vextabText">
                            </div>
                        </div>
                        <div>
                            {{sheet.description}}
                        </div>
                        {% endblock %}
                </div>
                {% endblock %}
                {% block sheet-input %}
                <div ng-show="false" >
                    <div >
                        <textarea ng-model="vextabText" >{{sheet.content}}</textarea>
                    </div>
                    
                </div>
                {% endblock %}
            </div>
        </div>
        {% endblock %}
    {% endblock %}
    {% block footer %}
    {% endblock %}

musicapp/templates/musicapp/test_form.html
<form action="{% url 'test_form' %}" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

musicapp/templates/musicapp/thanks.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>MusicPaste, Awesome, embeddable music TABs and scores with sound synthesis</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'musicapp/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'musicapp/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <style>
    .editable {
        width:95%;
        height: 100%;
        border-style: solid;
        border-width: 1px;
        
    }
    .editable:hover {
        background-color:#eeeeee;
    } 
    </style>
</head>

<body >
    <!--<nav class="navbar navbar-fixed-top navbar-inverse" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <a class="navbar-brand" href="#home">MusicPaste</a>
            </div>
        </div>
    </nav>-->
    <br/>
    <div class="container">

        <div class="row">
        
            <div class="col-lg-12 col-md-12">
            
                <h1 class="page-header">
                    <a href='/'>MusicPaste</a>
                    <small>The easiest way to create and share music</small>
                </h1>

            </div>

        </div>
        <hr>
        
        <div class="row">
            <div >
                <p>
                
                    Thank you for using MusicPaste! 
                </p>
                <p>
                    You will shortly receive an email with the links.
                </p>
            </div>
        </div>

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; <a href="musicpaste.com"> MusicPaste</a> 2014</p>
                </div>
            </div>
        </footer>

    </div>

    {% include "footer_ga.html" %}
</body>

</html>